import { expect, test } from "@playwright/test";

for (const width of [320, 390]) {
  test(`Task7 read-only transaction and card detail preserve canonical state at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 844 });
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto("/demo/entry");
    await expect(page).toHaveURL(/\/ledger\?month=2026-02$/);
    await page.goto("/cards?month=2026-02&tab=transactions&page=2");
    const before = page.url();
    const trigger = page.getByRole("button", { name: "거래 상세·수정", exact: true }).first();
    await trigger.click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toContainText("읽기 전용");
    await expect(dialog).toContainText("결제금액");
    await expect(dialog.locator("form")).toHaveCount(0);
    await expect(dialog.getByRole("button", { name: /저장|제외|취소 기록/ })).toHaveCount(0);
    expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`transaction-detail-${width}.png`) });
    await page.keyboard.press("Escape");
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toBeFocused();
    expect(page.url()).toBe(before);
    await page.goto("/cards/demo-everyday?month=2026-02&tab=transactions&query=%EC%83%9D%ED%99%9C&card=demo-everyday");
    await expect(page.getByRole("heading", { name: "전월 총실적과 자료 상태" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "목표 구간", exact: true })).toBeVisible();
    await expect(page.locator(".ledger-small-form")).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`card-detail-${width}.png`), fullPage: true });
    await page.getByRole("link", { name: "내 카드로 돌아가기", exact: true }).click();
    await expect(page).toHaveURL(/month=2026-02&tab=transactions&query=%EC%83%9D%ED%99%9C&card=demo-everyday$/);
    expect(errors).toEqual([]);
  });
}

const viewports = [{ width: 320, height: 800 }, { width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 1000 }];
for (const viewport of viewports) {
  test(`synthetic three tabs at ${viewport.width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto("/demo/entry");
    await expect(page.getByRole("heading", { name: "가계부", exact: true })).toBeVisible();
    await page.goto("/cards?month=2026-02&tab=performance");
    const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth && document.body.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
    await expect(page.locator(".workspace-card")).toHaveCount(3);
    await expect(page.locator('[data-card-id="demo-everyday"]')).toContainText("내 목표 달성");
    await expect(page.locator('[data-card-id="demo-everyday"]')).toContainText("381,000원");
    await expect(page.locator('[data-card-id="demo-transport"]')).toContainText("첫 구간까지");
    await expect(page.locator('[data-card-id="demo-transport"]')).toContainText("16,000원");
    await expect(page.locator('[data-card-id="demo-check"]')).toContainText("실적 조건 없음");
    await expect(page.locator('[data-card-id="demo-check"] [role="meter"]')).toHaveCount(0);
    await expect(page.locator('[data-card-id="demo-highest"], [data-card-id="demo-shared"], [data-card-id="demo-unknown"]')).toHaveCount(0);
    await noOverflow();
    const capture = async (name: string) => {
      await page.evaluate(() => window.scrollTo(0, 0));
      await page.screenshot({ path: testInfo.outputPath(`${name}-${viewport.width}-viewport.png`) });
      await page.screenshot({ path: testInfo.outputPath(`${name}-${viewport.width}.png`), fullPage: true });
    };
    await capture("performance");
    await page.getByRole("navigation", { name: "내 카드 보기" }).getByRole("link", { name: "혜택 관리" }).click();
    await expect(page).toHaveURL(/month=2026-02&tab=benefits/);
    await expect(page.locator(".benefit-total")).toHaveCount(3);
    await expect(page.locator(".benefit-total").nth(0)).toContainText("10,000원");
    await expect(page.locator(".benefit-total").nth(1)).toContainText("1,600원");
    await expect(page.locator(".benefit-total").nth(2)).toContainText("600원");
    await expect(page.getByRole("heading", { name: "한도 사용 현황", exact: true })).toBeVisible();
    await expect(page.getByText("이 달에 계산된 한도 내역이 없습니다. 미확인 한도를 무제한으로 간주하지 않습니다.", { exact: true })).toBeVisible();
    await noOverflow();
    await capture("benefits");
    await page.getByRole("navigation", { name: "내 카드 보기" }).getByRole("link", { name: "사용내역" }).click();
    await expect(page).toHaveURL(/month=2026-02&tab=transactions/);
    const total = page.locator(".activity-totals");
    await expect(total).toContainText("월 전체 승인 원금516,000원이번 달 환불 입금25,000원순 현금흐름 승인 − 환불491,000원");
    await expect(page.getByText("현재 검색·카드 필터의 월 전체 합계 · 56건. 페이지를 바꿔도 합계는 유지됩니다.", { exact: true })).toBeVisible();
    const totalText = await total.innerText();
    await noOverflow();
    await capture("activity");
    await page.getByRole("link", { name: "다음 50건" }).click();
    await expect(page).toHaveURL(/page=2/);
    await expect(page.locator(".workspace-activity > li")).toHaveCount(6);
    await expect(total).toHaveText(totalText, { useInnerText: true });
    await page.goBack();
    await expect(page).not.toHaveURL(/page=2/);
    await page.getByRole("combobox", { name: "결제 카드", exact: true }).selectOption("demo-everyday");
    await page.getByRole("button", { name: "검색", exact: true }).click();
    await expect(page).toHaveURL(/month=2026-02&tab=transactions.*card=demo-everyday/);
    await expect(page.locator(".activity-totals")).toContainText("월 전체 승인 원금396,000원이번 달 환불 입금25,000원순 현금흐름 승인 − 환불371,000원");
    await expect(page.getByText("현재 검색·카드 필터의 월 전체 합계 · 38건. 페이지를 바꿔도 합계는 유지됩니다.", { exact: true })).toBeVisible();
    await noOverflow();
    await page.goBack();
    await expect(page.getByRole("combobox", { name: "결제 카드", exact: true })).toHaveValue("");
    await expect(page.locator(".activity-totals")).toHaveText(totalText, { useInnerText: true });
    await page.getByRole("link", { name: "이전 달", exact: true }).click();
    await expect(page).toHaveURL(/month=2026-01&tab=transactions/);
    await expect(page.locator(".activity-totals")).toContainText("월 전체 승인 원금30,000원이번 달 환불 입금0원순 현금흐름 승인 − 환불30,000원");
    await expect(page.getByText("현재 검색·카드 필터의 월 전체 합계 · 1건. 페이지를 바꿔도 합계는 유지됩니다.", { exact: true })).toBeVisible();
    await capture("previous-month");
    await noOverflow();
    expect(errors).toEqual([]);
  });
}

test("canonical transactions and activity alias retain URL state in synthetic preview", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const noOverflow = async () => expect(await page.evaluate(() => document.body.scrollWidth <= document.documentElement.clientWidth && document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await page.goto("/demo/entry");
  await page.goto("/cards?month=2026-02&tab=transactions");
  await expect(page).toHaveURL(/month=2026-02&tab=transactions$/);
  await expect(page.getByRole("navigation", { name: "내 카드 보기" }).getByRole("link", { name: "사용내역" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("region", { name: "월 사용내역" })).toBeVisible();
  const total = await page.locator(".activity-totals").innerText();
  await page.getByRole("combobox", { name: "결제 카드", exact: true }).selectOption("demo-everyday");
  await page.getByRole("button", { name: "검색", exact: true }).click();
  await expect(page).toHaveURL(/month=2026-02&tab=transactions.*card=demo-everyday/);
  await expect(page.locator(".activity-totals")).toContainText("371,000원");
  await page.goBack();
  await expect(page.getByRole("combobox", { name: "결제 카드", exact: true })).toHaveValue("");
  await expect(page.locator(".activity-totals")).toHaveText(total, { useInnerText: true });
  await page.goto("/cards?month=2026-02&tab=activity&page=2");
  await expect(page).toHaveURL(/month=2026-02&tab=transactions&page=2$/);
  await expect(page.getByRole("link", { name: "이전 50건" })).toBeVisible();
  await expect(page.locator(".workspace-activity > li")).toHaveCount(6);
  await noOverflow();
  await page.screenshot({ path: testInfo.outputPath("transactions-alias-390.png"), fullPage: true });
  await page.getByRole("link", { name: "이전 달", exact: true }).click();
  await expect(page).toHaveURL(/month=2026-01&tab=transactions/);
  await expect(page.locator(".activity-totals")).toContainText("30,000원");
  await page.goto("/cards?month=2026-02&tab=performance");
  await expect(page.locator('[data-card-id="demo-everyday"]')).toContainText("381,000원");
  await expect(page.locator('[data-card-id="demo-check"]')).toContainText("실적 조건 없음");
  await noOverflow();
  await page.screenshot({ path: testInfo.outputPath("performance-390.png"), fullPage: true });
  await page.getByRole("navigation", { name: "내 카드 보기" }).getByRole("link", { name: "혜택 관리" }).click();
  await expect(page.locator(".benefit-total").nth(0)).toContainText("10,000원");
  await expect(page.getByText("이 달에 계산된 한도 내역이 없습니다. 미확인 한도를 무제한으로 간주하지 않습니다.", { exact: true })).toBeVisible();
  await noOverflow();
  await page.screenshot({ path: testInfo.outputPath("benefits-390.png"), fullPage: true });
  expect(errors).toEqual([]);
});

test("legacy demo entry preserves February across read-only entry, cards and search", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/demo/entry");
  await expect(page).toHaveURL(/\/ledger\?month=2026-02$/);
  const nav = page.getByRole("navigation", { name: "모바일 주 메뉴" });
  await expect(nav.getByRole("link")).toHaveText(["가계부", "통계", "카드"]);
  await expect(nav.getByRole("link", { name: "가계부", exact: true })).toHaveAttribute("aria-current", "page");
  await page.getByRole("button", { name: "내역 추가", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "새 내역 기록" });
  await expect(dialog).toContainText("읽기 전용");
  await expect(dialog.locator("form")).toHaveCount(0);
  await page.keyboard.press("Escape");
  await expect(nav.getByRole("link", { name: "카드", exact: true })).toHaveAttribute("href", /month=2026-02/);
  await nav.getByRole("link", { name: "카드", exact: true }).click();
  await expect(page).toHaveURL(/month=2026-02&tab=performance/);
  await page.getByRole("link", { name: "카드 찾기", exact: true }).click();
  await page.getByRole("textbox", { name: "카드사 또는 카드명" }).fill("생활");
  await page.getByRole("button", { name: "검색", exact: true }).click();
  await expect(page).toHaveURL(/month=2026-02/);
  await expect(page.getByText("Moniq 가상 생활비 카드", { exact: true })).toBeVisible();
  await expect(page.getByText("읽기 전용", { exact: false }).first()).toBeVisible();
  await page.getByRole("link", { name: "내 카드로 돌아가기" }).click();
  await expect(page).toHaveURL(/month=2026-02&tab=performance/);
});

test("search, month picker, keyboard tooltip and return from card detail", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/demo/entry");
  await page.goto("/cards?month=2026-02&tab=performance");
  const mark = page.getByRole("button", { name: /1구간 300,000원, 달성, 내 목표/ });
  await mark.focus();
  await expect(page.getByRole("tooltip")).toContainText("300,000원");
  expect(await mark.evaluate(element => getComputedStyle(element).outlineStyle)).not.toBe("none");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("tooltip")).toHaveCount(0);
  await page.keyboard.press("Tab");
  await expect(page.locator('[data-card-id="demo-everyday"]').getByRole("button", { name: /2구간 500,000원/ })).toBeFocused();
  await page.getByRole("textbox", { name: "카드 검색", exact: true }).fill("생활");
  await page.getByRole("button", { name: "검색", exact: true }).click();
  await expect(page.locator(".workspace-card")).toHaveCount(1);
  await expect(page).toHaveURL(/month=2026-02/);
  await page.locator(".workspace-card h2 a").click();
  await expect(page).toHaveURL(/cards\/demo-everyday\?month=2026-02/);
  await expect(page.getByRole("link", { name: "내 카드로 돌아가기" })).toBeVisible();
  await page.getByRole("link", { name: "내 카드로 돌아가기" }).click();
  await expect(page.locator(".workspace-card")).toHaveCount(1);
  await page.getByText("2026년 2월", { exact: true }).click();
  await page.getByLabel("조회할 월").fill("2026-01");
  await page.getByRole("button", { name: "이동", exact: true }).click();
  await expect(page).toHaveURL(/month=2026-01/);
  await page.goBack();
  await expect(page).toHaveURL(/month=2026-02/);
  await page.getByText("2026년 2월", { exact: true }).click();
  await expect(page.getByLabel("조회할 월")).toHaveValue("2026-02");
  await page.emulateMedia({ reducedMotion: "reduce", forcedColors: "active" });
  await page.goto("/cards?month=2026-02");
  await page.screenshot({ path: testInfo.outputPath("forced-colors-390.png"), fullPage: true });
  await expect(page.getByRole("meter").first()).toHaveAttribute("aria-valuenow", "381000");
});
